"""create user and habit tables

Revision ID: 8c7b7429f022
Revises: 068b26907eeb
Create Date: 2025-11-30 18:59:03.715756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7b7429f022'
down_revision: Union[str, Sequence[str], None] = '068b26907eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.String(), nullable=True))
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priorityenum'), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
